name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 python-is-python3 libncurses5-dev
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH

      - name: Sync Sources
        run: |
          export PATH=~/bin:$PATH
          mkdir fox_12.1
          cd fox_12.1
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b android-12.1
          repo sync -j$(nproc --all) --force-sync

      - name: Clone Device Tree
        run: |
          cd fox_12.1
          git clone https://github.com/Shahed420/Infinix_X6725B -b android-12.1 device/generic/X6725B

      - name: Build
        run: |
          cd fox_12.1
          export PATH=~/bin:$PATH
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_X6725B-eng || lunch omni_X6725B-eng
          make vendor_bootimage -j$(nproc --all)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-Infinix
          path: fox_12.1/out/target/product/X6725B/vendor_boot.img
